# Generated by Django 5.2.9 on 2025-12-29 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Produto Físico'), ('S', 'Serviço (Mão de Obra)')], default='P', max_length=1, verbose_name='Tipo do Item')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto/Serviço')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Venda')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.IntegerField(default=5, verbose_name='Estoque Mínimo (Alerta)')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras / GTIN')),
                ('referencia_fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cód. Fabricante')),
                ('local_fisico', models.CharField(blank=True, help_text='Ex: Prateleira A1, Gaveta 2', max_length=100, null=True, verbose_name='Localização no Estoque')),
                ('controlar_num_serie', models.BooleanField(default=False, verbose_name='Exigir Nº Série na Venda?')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade (se aplicável)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto / Serviço',
                'verbose_name_plural': 'Produtos e Serviços',
                'ordering': ['nome'],
            },
        ),
    ]
