# Generated by Django 5.2.9 on 2025-12-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='garantia_meses',
            field=models.IntegerField(default=3, help_text='Tempo de garantia oferecido ao cliente (ex: 3, 12, 24)', verbose_name='Garantia (Meses)'),
        ),
    ]
