# Generated by Django 5.2.9 on 2025-12-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Nome da Sua Empresa', max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, help_text='Idealmente uma imagem retangular ou quadrada de alta resolução.', null=True, upload_to='config/logos/', verbose_name='Logomarca do Cabeçalho')),
                ('endereco_completo', models.CharField(default='Rua Exemplo, 123 - Bairro - Cidade/UF', max_length=255, verbose_name='Linha de Endereço')),
                ('contato_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('contato_telefone', models.CharField(default='(XX) 99999-9999', max_length=50, verbose_name='Telefones')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site/Instagram')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configuração do Sistema',
            },
        ),
    ]
