# Generated by Django 5.2.9 on 2025-12-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total dos Itens'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Serviço/Peças'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Final'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Líquido'),
        ),
    ]
