# Generated by Django 5.2.9 on 2025-12-29 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo / Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cpf_cnpj', models.CharField(help_text='Insira apenas números', max_length=20, unique=True, verbose_name='CPF / CNPJ')),
                ('rg_ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG / Inscrição Estadual')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone Principal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tecnico_responsavel', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContatoSecundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Contato')),
                ('cargo_parentesco', models.CharField(help_text='Ex: Esposa, Gerente, Vizinho', max_length=50, verbose_name='Cargo / Parentesco')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_secundarios', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contato Secundário',
                'verbose_name_plural': 'Contatos Secundários',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Principal', help_text='Ex: Casa, Escritório, Loja Centro', max_length=50, verbose_name='Descrição do Local')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Rua/Av')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(default='BA', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
